=begin
#BitbarCloud API

#BitbarCloud API.

OpenAPI spec version: 2.100.0
Contact: damian.sniezek@smartbear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for BitbarCloudApiClient::HiddenApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HiddenApi' do
  before do
    # run before each test
    @instance = BitbarCloudApiClient::HiddenApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HiddenApi' do
    it 'should create an instance of HiddenApi' do
      expect(@instance).to be_instance_of(BitbarCloudApiClient::HiddenApi)
    end
  end

  # unit tests for validate_credentials_using_post
  # Validate credentials.
  # @param email email
  # @param password password
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'validate_credentials_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
