=begin
#BitbarCloud API

#BitbarCloud API.

OpenAPI spec version: 2.87.0
Contact: support@bitbar.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for BitbarCloudApiClient::ProjectsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectsApi' do
  before do
    # run before each test
    @instance = BitbarCloudApiClient::ProjectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectsApi' do
    it 'should create an instance of ProjectsApi' do
      expect(@instance).to be_instance_of(BitbarCloudApiClient::ProjectsApi)
    end
  end

  # unit tests for create_my_project_using_post
  # Create project.
  # @param user_id userId
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :app_crawler_run appCrawlerRun
  # @option opts [String] :mode mode
  # @option opts [String] :name name
  # @option opts [String] :type type
  # @return [APIProject]
  describe 'create_my_project_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_user_project_using_delete
  # Delete project.
  # @param project_id projectId
  # @param user_id userId
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_user_project_using_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_project_using_get
  # Get project.
  # @param project_id projectId
  # @param user_id userId
  # @param [Hash] opts the optional parameters
  # @return [APIProject]
  describe 'get_user_project_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_projects_using_get
  # Get projects.
  # @param user_id userId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter filter parameter contains list of fields used for filter query result &lt;br&gt; examples: &lt;br&gt; filter&#x3D;archivetime_eq_1576134484593&lt;br&gt;filter&#x3D;common_eq_null&lt;br&gt;filter&#x3D;createtime_eq_1576134484593&lt;br&gt;filter&#x3D;ostype_eq_ios&lt;br&gt;filter&#x3D;name_eq_value&lt;br&gt;filter&#x3D;description_eq_value&lt;br&gt;filter&#x3D;readonly_eq_true&lt;br&gt;filter&#x3D;id_eq_1&lt;br&gt;filter&#x3D;sharedbyemail_eq_value
  # @option opts [Integer] :limit limit parameter define page size
  # @option opts [Integer] :offset offset parameter define page number
  # @option opts [BOOLEAN] :show_statistics showStatistics
  # @option opts [BOOLEAN] :skip_common_project skipCommonProject
  # @option opts [BOOLEAN] :skip_shared skipShared
  # @option opts [String] :sort sort parameter contains list of fields used for sort query result &lt;br&gt; examples: &lt;br&gt; sort&#x3D;archiveTime_a&lt;br&gt;sort&#x3D;common_a&lt;br&gt;sort&#x3D;createTime_a&lt;br&gt;sort&#x3D;osType_a&lt;br&gt;sort&#x3D;name_a&lt;br&gt;sort&#x3D;description_a&lt;br&gt;sort&#x3D;id_a&lt;br&gt;sort&#x3D;type_a&lt;br&gt;sort&#x3D;sharedByEmail_a
  # @option opts [BOOLEAN] :with_additional_users withAdditionalUsers
  # @return [APIListOfAPIProject]
  describe 'get_user_projects_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_user_project_using_post
  # Update project.
  # @param project_id projectId
  # @param user_id userId
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :archiving_item_count archivingItemCount
  # @option opts [String] :archiving_strategy archivingStrategy
  # @option opts [BOOLEAN] :common common
  # @option opts [String] :description description
  # @option opts [String] :name name
  # @return [APIProject]
  describe 'update_user_project_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
