=begin
#BitbarCloud API

#BitbarCloud API.

OpenAPI spec version: 2.100.0
Contact: damian.sniezek@smartbear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BitbarCloudApiClient::CTSLicense
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CTSLicense' do
  before do
    # run before each test
    @instance = BitbarCloudApiClient::CTSLicense.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CTSLicense' do
    it 'should create an instance of CTSLicense' do
      expect(@instance).to be_instance_of(BitbarCloudApiClient::CTSLicense)
    end
  end
  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
