=begin
#BitbarCloud API

#BitbarCloud API

OpenAPI spec version: 3.24.1-master-20231027-124207

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BitbarCloudApiClient::UserIdFeedbackBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserIdFeedbackBody' do
  before do
    # run before each test
    @instance = BitbarCloudApiClient::UserIdFeedbackBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserIdFeedbackBody' do
    it 'should create an instance of UserIdFeedbackBody' do
      expect(@instance).to be_instance_of(BitbarCloudApiClient::UserIdFeedbackBody)
    end
  end
  describe 'test attribute "file"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
