=begin
#BitbarCloud API

#BitbarCloud API.

OpenAPI spec version: 2.87.0
Contact: support@bitbar.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'date'

module BitbarCloudApiClient
  class APIService
    attr_accessor :activate_time

    attr_accessor :activated

    attr_accessor :archive_time

    attr_accessor :auto_renew

    attr_accessor :cent_price

    attr_accessor :charge_type

    attr_accessor :custom_plan

    attr_accessor :description

    attr_accessor :external_id

    attr_accessor :id

    attr_accessor :included_hours

    attr_accessor :name

    attr_accessor :price_per_hour

    attr_accessor :price_string

    attr_accessor :roles

    attr_accessor :self_uri

    attr_accessor :unit

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'activate_time' => :'activateTime',
        :'activated' => :'activated',
        :'archive_time' => :'archiveTime',
        :'auto_renew' => :'autoRenew',
        :'cent_price' => :'centPrice',
        :'charge_type' => :'chargeType',
        :'custom_plan' => :'customPlan',
        :'description' => :'description',
        :'external_id' => :'externalId',
        :'id' => :'id',
        :'included_hours' => :'includedHours',
        :'name' => :'name',
        :'price_per_hour' => :'pricePerHour',
        :'price_string' => :'priceString',
        :'roles' => :'roles',
        :'self_uri' => :'selfURI',
        :'unit' => :'unit'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'activate_time' => :'DateTime',
        :'activated' => :'BOOLEAN',
        :'archive_time' => :'DateTime',
        :'auto_renew' => :'BOOLEAN',
        :'cent_price' => :'Integer',
        :'charge_type' => :'String',
        :'custom_plan' => :'BOOLEAN',
        :'description' => :'String',
        :'external_id' => :'String',
        :'id' => :'Integer',
        :'included_hours' => :'Integer',
        :'name' => :'String',
        :'price_per_hour' => :'Integer',
        :'price_string' => :'String',
        :'roles' => :'Array<APIRole>',
        :'self_uri' => :'String',
        :'unit' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'activateTime')
        self.activate_time = attributes[:'activateTime']
      end

      if attributes.has_key?(:'activated')
        self.activated = attributes[:'activated']
      end

      if attributes.has_key?(:'archiveTime')
        self.archive_time = attributes[:'archiveTime']
      end

      if attributes.has_key?(:'autoRenew')
        self.auto_renew = attributes[:'autoRenew']
      end

      if attributes.has_key?(:'centPrice')
        self.cent_price = attributes[:'centPrice']
      end

      if attributes.has_key?(:'chargeType')
        self.charge_type = attributes[:'chargeType']
      end

      if attributes.has_key?(:'customPlan')
        self.custom_plan = attributes[:'customPlan']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'externalId')
        self.external_id = attributes[:'externalId']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'includedHours')
        self.included_hours = attributes[:'includedHours']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'pricePerHour')
        self.price_per_hour = attributes[:'pricePerHour']
      end

      if attributes.has_key?(:'priceString')
        self.price_string = attributes[:'priceString']
      end

      if attributes.has_key?(:'roles')
        if (value = attributes[:'roles']).is_a?(Array)
          self.roles = value
        end
      end

      if attributes.has_key?(:'selfURI')
        self.self_uri = attributes[:'selfURI']
      end

      if attributes.has_key?(:'unit')
        self.unit = attributes[:'unit']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      charge_type_validator = EnumAttributeValidator.new('String', ['USAGE', 'CONCURRENCY'])
      return false unless charge_type_validator.valid?(@charge_type)
      unit_validator = EnumAttributeValidator.new('String', ['MONTH', 'DAY', 'YEAR', 'HOUR', 'RUN', 'PROJECT'])
      return false unless unit_validator.valid?(@unit)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] charge_type Object to be assigned
    def charge_type=(charge_type)
      validator = EnumAttributeValidator.new('String', ['USAGE', 'CONCURRENCY'])
      unless validator.valid?(charge_type)
        fail ArgumentError, 'invalid value for "charge_type", must be one of #{validator.allowable_values}.'
      end
      @charge_type = charge_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] unit Object to be assigned
    def unit=(unit)
      validator = EnumAttributeValidator.new('String', ['MONTH', 'DAY', 'YEAR', 'HOUR', 'RUN', 'PROJECT'])
      unless validator.valid?(unit)
        fail ArgumentError, 'invalid value for "unit", must be one of #{validator.allowable_values}.'
      end
      @unit = unit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          activate_time == o.activate_time &&
          activated == o.activated &&
          archive_time == o.archive_time &&
          auto_renew == o.auto_renew &&
          cent_price == o.cent_price &&
          charge_type == o.charge_type &&
          custom_plan == o.custom_plan &&
          description == o.description &&
          external_id == o.external_id &&
          id == o.id &&
          included_hours == o.included_hours &&
          name == o.name &&
          price_per_hour == o.price_per_hour &&
          price_string == o.price_string &&
          roles == o.roles &&
          self_uri == o.self_uri &&
          unit == o.unit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [activate_time, activated, archive_time, auto_renew, cent_price, charge_type, custom_plan, description, external_id, id, included_hours, name, price_per_hour, price_string, roles, self_uri, unit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = BitbarCloudApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
