=begin
#BitbarCloud API

#BitbarCloud API

OpenAPI spec version: 3.24.1-master-20231027-124207

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'date'

module BitbarCloudApiClient
  class APIAdminTestRun
    attr_accessor :id

    attr_accessor :self_uri

    attr_accessor :create_time

    attr_accessor :end_time

    attr_accessor :state

    attr_accessor :success_ratio

    attr_accessor :priority

    attr_accessor :project_name

    attr_accessor :start_time

    attr_accessor :test_run_name

    attr_accessor :started_by_id

    attr_accessor :user_name

    attr_accessor :project_id

    attr_accessor :duration

    attr_accessor :scheduler

    attr_accessor :framework_id

    attr_accessor :framework_name

    attr_accessor :message

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'self_uri' => :'selfURI',
        :'create_time' => :'createTime',
        :'end_time' => :'endTime',
        :'state' => :'state',
        :'success_ratio' => :'successRatio',
        :'priority' => :'priority',
        :'project_name' => :'projectName',
        :'start_time' => :'startTime',
        :'test_run_name' => :'testRunName',
        :'started_by_id' => :'startedById',
        :'user_name' => :'userName',
        :'project_id' => :'projectId',
        :'duration' => :'duration',
        :'scheduler' => :'scheduler',
        :'framework_id' => :'frameworkId',
        :'framework_name' => :'frameworkName',
        :'message' => :'message'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Object',
        :'self_uri' => :'Object',
        :'create_time' => :'Object',
        :'end_time' => :'Object',
        :'state' => :'Object',
        :'success_ratio' => :'Object',
        :'priority' => :'Object',
        :'project_name' => :'Object',
        :'start_time' => :'Object',
        :'test_run_name' => :'Object',
        :'started_by_id' => :'Object',
        :'user_name' => :'Object',
        :'project_id' => :'Object',
        :'duration' => :'Object',
        :'scheduler' => :'Object',
        :'framework_id' => :'Object',
        :'framework_name' => :'Object',
        :'message' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BitbarCloudApiClient::APIAdminTestRun` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BitbarCloudApiClient::APIAdminTestRun`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'self_uri')
        self.self_uri = attributes[:'self_uri']
      end

      if attributes.key?(:'create_time')
        self.create_time = attributes[:'create_time']
      end

      if attributes.key?(:'end_time')
        self.end_time = attributes[:'end_time']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'success_ratio')
        self.success_ratio = attributes[:'success_ratio']
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      end

      if attributes.key?(:'project_name')
        self.project_name = attributes[:'project_name']
      end

      if attributes.key?(:'start_time')
        self.start_time = attributes[:'start_time']
      end

      if attributes.key?(:'test_run_name')
        self.test_run_name = attributes[:'test_run_name']
      end

      if attributes.key?(:'started_by_id')
        self.started_by_id = attributes[:'started_by_id']
      end

      if attributes.key?(:'user_name')
        self.user_name = attributes[:'user_name']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      end

      if attributes.key?(:'scheduler')
        self.scheduler = attributes[:'scheduler']
      end

      if attributes.key?(:'framework_id')
        self.framework_id = attributes[:'framework_id']
      end

      if attributes.key?(:'framework_name')
        self.framework_name = attributes[:'framework_name']
      end

      if attributes.key?(:'message')
        self.message = attributes[:'message']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      state_validator = EnumAttributeValidator.new('Object', ['WAITING', 'RUNNING', 'FINISHED'])
      return false unless state_validator.valid?(@state)
      scheduler_validator = EnumAttributeValidator.new('Object', ['PARALLEL', 'SERIAL', 'SINGLE', 'ALL_INSTANCES'])
      return false unless scheduler_validator.valid?(@scheduler)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('Object', ['WAITING', 'RUNNING', 'FINISHED'])
      unless validator.valid?(state)
        fail ArgumentError, "invalid value for \"state\", must be one of #{validator.allowable_values}."
      end
      @state = state
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] scheduler Object to be assigned
    def scheduler=(scheduler)
      validator = EnumAttributeValidator.new('Object', ['PARALLEL', 'SERIAL', 'SINGLE', 'ALL_INSTANCES'])
      unless validator.valid?(scheduler)
        fail ArgumentError, "invalid value for \"scheduler\", must be one of #{validator.allowable_values}."
      end
      @scheduler = scheduler
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          self_uri == o.self_uri &&
          create_time == o.create_time &&
          end_time == o.end_time &&
          state == o.state &&
          success_ratio == o.success_ratio &&
          priority == o.priority &&
          project_name == o.project_name &&
          start_time == o.start_time &&
          test_run_name == o.test_run_name &&
          started_by_id == o.started_by_id &&
          user_name == o.user_name &&
          project_id == o.project_id &&
          duration == o.duration &&
          scheduler == o.scheduler &&
          framework_id == o.framework_id &&
          framework_name == o.framework_name &&
          message == o.message
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, self_uri, create_time, end_time, state, success_ratio, priority, project_name, start_time, test_run_name, started_by_id, user_name, project_id, duration, scheduler, framework_id, framework_name, message].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        BitbarCloudApiClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
